export const environment = {
	production: true,
	account:'ACCOUNT',
	agdomain:'AGDOMAIN',
	apikey:'APIKEY',
	appmetrics:'APPMETRICS',
	clientId: 'ERPACLIENTID',
	emaildomainsaasclient: 'EMAILDOMAINSAAS',
	identityPoolId: '',
	inframetrics:'INFRAMETRICS',
	region : 'REGION',
	restapiid : 'RESTAPIID',
	saasclientId: 'SAASCLIENTID', 
	saasclientuserPoolId: 'SAASPOOLID',
	stage:'STAGE',
	userPoolId: 'ERPAPOOLID',
	apigw_domain : "APIGW_DOMAIN",
	fileuploaddomain:'FILEUPLOADDOMAIN',
	saas_bucket:"SAAS_BUCKET",
	authToken:"AUTHTOKEN",

	// account:'729444515875',
	// agdomain:'null',
	// apikey:'mQZ90CldlfGA8NjgQ9id3o9dcRUOEg1LyGsK5NVy0fWteqzyF2',
	// appmetrics:'https://cloudwatch.amazonaws.com/dashboard.html?dashboard=agdm-application-dashboard&context=eyJSIjoidXMtZWFzdC0xIiwiRCI6ImN3LWRiLTcyOTQ0NDUxNTg3NSIsIlUiOiJ1cy1lYXN0LTFfWXZ5NHFzSElnIiwiQyI6IjdobzRwZTlscHJnOGttZjY2MDQ4amc3bjRsIiwiSSI6InVzLWVhc3QtMTo2NmQyNDdiMi01MmE0LTRmYmMtODNkZC1iNDAwNjkzMTFkYWYiLCJPIjoiYXJuOmF3czppYW06OjcyOTQ0NDUxNTg3NTpyb2xlL3NlcnZpY2Utcm9sZS9DV0RCU2hhcmluZy1QdWJsaWNSZWFkT25seUFjY2Vzcy1BRUtFMDVYSSIsIk0iOiJQdWJsaWMifQ==',
	// clientId: '4f6g2eokq1uffv3k5inuqpd9q9',
	// emaildomainsaasclient: 'gmail.com',
	// identityPoolId: '',
	// inframetrics:'https://cloudwatch.amazonaws.com/dashboard.html?dashboard=agdm-infra-dashboard&context=eyJSIjoidXMtZWFzdC0xIiwiRCI6ImN3LWRiLTcyOTQ0NDUxNTg3NSIsIlUiOiJ1cy1lYXN0LTFfWXZ5NHFzSElnIiwiQyI6IjdobzRwZTlscHJnOGttZjY2MDQ4amc3bjRsIiwiSSI6InVzLWVhc3QtMTozNDMzOTE1Mi00MmEzLTRmMzQtYmI3NS1hYjYxMWExYjNlMTEiLCJPIjoiYXJuOmF3czppYW06OjcyOTQ0NDUxNTg3NTpyb2xlL3NlcnZpY2Utcm9sZS9DV0RCU2hhcmluZy1QdWJsaWNSZWFkT25seUFjY2Vzcy1ZV1VTODM4RiIsIk0iOiJQdWJsaWMifQ==',
	// region : 'us-east-2',
	// restapiid : 'pd5ldhbc03',
	// saasclientId: '5ai0p01t739ib1lso55j68pama', 
	// saasclientuserPoolId: 'us-east-2_YrLSTaCc6',
	// stage:'v1',
	// userPoolId: 'us-east-2_w3qSe8eIh',
	// apigw_domain : "api-agsaasohio.active-genie.com",
	// fileuploaddomain:'api-agsaasohio-s3.active-genie.com',
	// saas_bucket:'agsaasohio-artifacts-20231024170431344300000001',
	// authToken:"wkh29aas76yrw7t3spv6nr90uf47zqtc",

	rekognitionBucket: '',
	albumName: "",
	ddbTableName: 'LoginTrail',
	// bucketRegion: bucketRegion,
	cognito_idp_endpoint: '',
	cognito_identity_endpoint: '',
	sts_endpoint: '',
	dynamodb_endpoint: '',
	s3_endpoint: '',
}

