export const environment = {
	production: true,
	identityPoolId: '',
	userPoolId: 'USERPOOLID',
	clientId: 'CLIENTID', 
	saasclientuserPoolId: 'SAASCLIENTUSERPOOLID',
	saasclientId: 'SAASCLIENTID', 
	agdomain:'AGDOMAIN',
	restapiid : 'RESTAPIID',
	region : 'REGION',
	account:'ACCOUNT',
	stage:'STAGE',
	apikey:'APIKEY',
	inframetrics:'INFRAMETRICS',
	appmetrics:'APPMETRICS',

	// userPoolId: 'us-east-2_fNxpvcps0',
	// restapiid : 'k257h4hgpj',
	// clientId: '589df8i2adh4437cq1tgb72ung',
	// agdomain:'erpasandbox.com',
	// region : 'us-east-2',
	// account:'729444515875',
	// stage:'v1',
	// apikey:'9pwVR0PrMABrxv4lgnIICjidCCiE1hRjSAwUtFaM22pXSLFNBF',
	// inframetrics:'https://cloudwatch.amazonaws.com/dashboard.html?dashboard=agdm-infra-dashboard&context=eyJSIjoidXMtZWFzdC0xIiwiRCI6ImN3LWRiLTcyOTQ0NDUxNTg3NSIsIlUiOiJ1cy1lYXN0LTFfWXZ5NHFzSElnIiwiQyI6IjdobzRwZTlscHJnOGttZjY2MDQ4amc3bjRsIiwiSSI6InVzLWVhc3QtMTozNDMzOTE1Mi00MmEzLTRmMzQtYmI3NS1hYjYxMWExYjNlMTEiLCJPIjoiYXJuOmF3czppYW06OjcyOTQ0NDUxNTg3NTpyb2xlL3NlcnZpY2Utcm9sZS9DV0RCU2hhcmluZy1QdWJsaWNSZWFkT25seUFjY2Vzcy1ZV1VTODM4RiIsIk0iOiJQdWJsaWMifQ==',
	// appmetrics:'https://cloudwatch.amazonaws.com/dashboard.html?dashboard=agdm-application-dashboard&context=eyJSIjoidXMtZWFzdC0xIiwiRCI6ImN3LWRiLTcyOTQ0NDUxNTg3NSIsIlUiOiJ1cy1lYXN0LTFfWXZ5NHFzSElnIiwiQyI6IjdobzRwZTlscHJnOGttZjY2MDQ4amc3bjRsIiwiSSI6InVzLWVhc3QtMTo2NmQyNDdiMi01MmE0LTRmYmMtODNkZC1iNDAwNjkzMTFkYWYiLCJPIjoiYXJuOmF3czppYW06OjcyOTQ0NDUxNTg3NTpyb2xlL3NlcnZpY2Utcm9sZS9DV0RCU2hhcmluZy1QdWJsaWNSZWFkT25seUFjY2Vzcy1BRUtFMDVYSSIsIk0iOiJQdWJsaWMifQ==',

	rekognitionBucket: '',
	albumName: "",
	ddbTableName: 'LoginTrail',
	// bucketRegion: bucketRegion,
	cognito_idp_endpoint: '',
	cognito_identity_endpoint: '',
	sts_endpoint: '',
	dynamodb_endpoint: '',
	s3_endpoint: '',
}

